name: epidemics-tfg
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=51_gnu
  - anyio=4.10.0=py312hd43f75c_0
  - aom=3.12.1=h419075a_0
  - argon2-cffi=25.1.0=py312hd43f75c_0
  - argon2-cffi-bindings=25.1.0=py312ha28494d_0
  - asttokens=3.0.0=py312hd43f75c_0
  - async-lru=2.0.5=py312hd43f75c_0
  - attrs=25.4.0=py312hd43f75c_2
  - babel=2.17.0=py312hd43f75c_0
  - beautifulsoup4=4.14.2=py312hd43f75c_0
  - blas=1.0=openblas
  - bleach=6.3.0=py312hd43f75c_0
  - bottleneck=1.4.2=py312h3a5b157_1
  - brotlicffi=1.2.0.0=py312h5b11e9f_0
  - bzip2=1.0.8=h998d150_6
  - ca-certificates=2025.12.2=hd43f75c_0
  - cairo=1.18.4=hd97bfd3_0
  - certifi=2025.11.12=py312hd43f75c_0
  - cffi=2.0.0=py312h2d8c4a8_1
  - charset-normalizer=3.4.4=py312hd43f75c_0
  - comm=0.2.3=py312hd43f75c_0
  - contourpy=1.3.3=py312hb8fdbf2_0
  - cycler=0.12.1=py312hd43f75c_0
  - dav1d=1.2.1=h998d150_0
  - debugpy=1.8.16=py312hd80b68a_1
  - decorator=5.2.1=py312hd43f75c_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - executing=2.2.1=py312hd43f75c_0
  - expat=2.7.3=h5b11e9f_4
  - fontconfig=2.15.0=hfa97f67_0
  - fonttools=4.61.0=py312h27118de_0
  - freetype=2.13.3=h6df46f4_0
  - fribidi=1.0.10=hfd63f10_0
  - gmp=6.3.0=h419075a_0
  - gmpy2=2.2.2=py312h6d033b1_0
  - graphite2=1.3.14=h22f4aa5_1
  - h11=0.16.0=py312hd43f75c_1
  - harfbuzz=10.2.0=h6cf3ae6_1
  - html5lib=1.1=pyhd3eb1b0_0
  - httpcore=1.0.9=py312hd43f75c_0
  - httpx=0.28.1=py312hd43f75c_1
  - icu=73.1=h419075a_0
  - idna=3.11=py312hd43f75c_0
  - ipykernel=6.31.0=py312had16b7f_0
  - ipython=9.7.0=py312hd43f75c_0
  - ipython_pygments_lexers=1.1.1=py312hd43f75c_0
  - ipywidgets=8.1.7=py312hd43f75c_0
  - jedi=0.19.2=py312hd43f75c_0
  - jinja2=3.1.6=py312hd43f75c_0
  - jpeg=9f=h31cb85b_0
  - json5=0.12.1=py312hd43f75c_0
  - jsonschema=4.25.0=py312hd43f75c_1
  - jsonschema-specifications=2025.9.1=py312hd43f75c_0
  - jupyter=1.1.1=py312hd43f75c_0
  - jupyter-lsp=2.2.5=py312hd43f75c_0
  - jupyter_client=8.6.3=py312hd43f75c_1
  - jupyter_console=6.6.3=py312hd43f75c_1
  - jupyter_core=5.9.1=py312hd43f75c_0
  - jupyter_events=0.12.0=py312hd43f75c_1
  - jupyter_server=2.17.0=py312hd43f75c_0
  - jupyter_server_terminals=0.5.3=py312hd43f75c_0
  - jupyterlab=4.5.0=py312hd43f75c_0
  - jupyterlab_pygments=0.3.0=py312hd43f75c_0
  - jupyterlab_server=2.28.0=py312hd43f75c_0
  - jupyterlab_widgets=3.0.15=py312hd43f75c_0
  - kiwisolver=1.4.9=py312h86909b6_0
  - lcms2=2.17=he39284c_0
  - ld_impl_linux-aarch64=2.44=h4e4ac68_2
  - lerc=4.0.0=h419075a_0
  - libavif=1.3.0=h462c9e6_0
  - libdeflate=1.22=h998d150_0
  - libexpat=2.7.3=h5b11e9f_4
  - libffi=3.4.4=h419075a_1
  - libgcc=15.2.0=hc18542e_7
  - libgcc-ng=15.2.0=h51576c1_7
  - libgfortran=15.2.0=h51576c1_7
  - libgfortran-ng=15.2.0=h51576c1_7
  - libgfortran5=15.2.0=hdc851ad_7
  - libglib=2.84.4=h481f47d_0
  - libgomp=15.2.0=hf47c802_7
  - libiconv=1.16=h998d150_3
  - libnsl=2.0.0=h998d150_0
  - libopenblas=0.3.30=h90745d9_2
  - libopenjpeg=2.5.4=ha28494d_1
  - libpng=1.6.50=h01b5ae2_0
  - libsodium=1.0.20=he1d2cb3_0
  - libstdcxx=15.2.0=h9538471_7
  - libstdcxx-ng=15.2.0=h719ae8e_7
  - libtiff=4.7.1=hf31298c_0
  - libuuid=1.41.5=h998d150_0
  - libwebp-base=1.6.0=h6c56547_0
  - libxcb=1.17.0=hf66535e_0
  - libxml2=2.13.9=h729a2f8_0
  - libzlib=1.3.1=h998d150_0
  - lz4-c=1.9.4=h419075a_1
  - markupsafe=3.0.2=py312h998d150_0
  - matplotlib=3.10.7=py312hd43f75c_0
  - matplotlib-base=3.10.7=py312hfbd568f_0
  - matplotlib-inline=0.2.1=py312hd43f75c_0
  - mistune=3.1.2=py312hd43f75c_0
  - mpc=1.3.1=h998d150_0
  - mpfr=4.2.1=h998d150_0
  - mpmath=1.3.0=py312hd43f75c_0
  - nbclient=0.10.2=py312hd43f75c_0
  - nbconvert=7.16.6=py312hd43f75c_0
  - nbconvert-core=7.16.6=py312hd43f75c_0
  - nbconvert-pandoc=7.16.6=py312hd43f75c_0
  - nbformat=5.10.4=py312hd43f75c_0
  - ncurses=6.5=h419075a_0
  - nest-asyncio=1.6.0=py312hd43f75c_0
  - notebook=7.5.0=py312hd43f75c_0
  - notebook-shim=0.2.4=py312hd43f75c_0
  - numexpr=2.14.1=py312h3869fce_0
  - numpy=2.3.5=py312hd965a70_0
  - numpy-base=2.3.5=py312h9f084ca_0
  - openssl=3.0.18=h8a9c3cf_0
  - packaging=25.0=py312hd43f75c_1
  - pandas=2.3.3=py312he07b0ad_1
  - pandoc=3.8=hd43f75c_0
  - pandocfilters=1.5.1=py312hd43f75c_0
  - parso=0.8.5=py312hd43f75c_0
  - pcre2=10.46=h1746348_0
  - pexpect=4.9.0=py312hd43f75c_1
  - pillow=12.0.0=py312h736d0cf_1
  - pip=25.3=pyhc872135_0
  - pixman=0.46.4=h419075a_0
  - platformdirs=4.5.0=py312hd43f75c_0
  - prometheus_client=0.21.1=py312hd43f75c_0
  - prompt-toolkit=3.0.52=py312hd43f75c_1
  - prompt_toolkit=3.0.52=hd3eb1b0_1
  - psutil=7.0.0=py312ha28494d_1
  - pthread-stubs=0.3=hfd63f10_1
  - ptyprocess=0.7.0=pyhd3eb1b0_3
  - pure_eval=0.2.3=py312hd43f75c_0
  - pycparser=2.23=py312hd43f75c_0
  - pygments=2.19.2=py312hd43f75c_0
  - pyparsing=3.2.5=py312hd43f75c_0
  - pysocks=1.7.1=py312hd43f75c_1
  - python=3.12.12=h71d72b8_1
  - python-dateutil=2.9.0post0=py312hd43f75c_2
  - python-fastjsonschema=2.21.2=py312hd43f75c_0
  - python-json-logger=4.0.0=py312hd43f75c_0
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - pytz=2025.2=py312hd43f75c_0
  - pyyaml=6.0.3=py312hbd8301c_0
  - pyzmq=27.1.0=py312h2252cf7_1
  - qtconsole=5.7.0=py312hd43f75c_0
  - qtpy=2.4.3=py312hd43f75c_0
  - readline=8.3=h886d1d0_0
  - referencing=0.37.0=py312hd43f75c_0
  - requests=2.32.5=py312hd43f75c_1
  - rfc3339-validator=0.1.4=py312hd43f75c_0
  - rfc3986-validator=0.1.1=py312hd43f75c_0
  - rpds-py=0.28.0=py312hff451be_0
  - scipy=1.16.3=py312h38916ec_0
  - send2trash=1.8.2=py312hd43f75c_1
  - setuptools=80.9.0=py312hd43f75c_0
  - six=1.17.0=py312hd43f75c_0
  - sniffio=1.3.1=py312hd43f75c_0
  - soupsieve=2.5=py312hd43f75c_0
  - sqlite=3.51.0=hc5b20ee_0
  - stack_data=0.6.3=py312hd43f75c_0
  - sympy=1.14.0=py312hd43f75c_1
  - terminado=0.18.1=py312hd43f75c_0
  - tinycss2=1.4.0=py312hd43f75c_0
  - tk=8.6.15=h987d8db_0
  - tornado=6.5.4=py312h27118de_0
  - tqdm=4.67.1=py312had16b7f_1
  - traitlets=5.14.3=py312hd43f75c_0
  - typing-extensions=4.15.0=py312hd43f75c_0
  - typing_extensions=4.15.0=py312hd43f75c_0
  - tzdata=2025b=h04d1e81_0
  - urllib3=2.6.1=py312hd43f75c_0
  - wcwidth=0.2.13=py312hd43f75c_0
  - webencodings=0.5.1=py312hd43f75c_2
  - websocket-client=1.8.0=py312hd43f75c_0
  - wheel=0.45.1=py312hd43f75c_0
  - widgetsnbextension=4.0.14=py312hd43f75c_0
  - xorg-libx11=1.8.12=hf66535e_1
  - xorg-libxau=1.0.12=hf66535e_0
  - xorg-libxdmcp=1.1.5=hf66535e_0
  - xorg-libxext=1.3.6=hf66535e_0
  - xorg-libxrender=0.9.12=hf66535e_0
  - xorg-xorgproto=2024.1=h998d150_1
  - xz=5.6.4=h998d150_1
  - yaml=0.2.5=hfd63f10_0
  - zeromq=4.3.5=hb793f1b_1
  - zlib=1.3.1=h998d150_0
  - zstd=1.5.7=hc8aa508_0
prefix: /home/adria/miniconda3/envs/epidemics-tfg
